=== pitecus/meirelles/src/assets/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "definitions": {
    "iso8601": {
      "description": "e.g. 2014-06-29",
      "pattern": "^([1-2][0-9]{3}-[0-1][0-9]-[0-3][0-9]|[1-2][0-9]{3}-[0-1][0-9]|[1-2][0-9]{3})$",
      "type": "string"
    }
  },
  "properties": {
    "$schema": {
      "description": "link to the version of the schema that can validate the resume",
      "format": "uri",
      "type": "string"
    },
    "awards": {
      "additionalItems": false,
      "description": "Specify any awards you have received throughout your professional career",
      "items": {
        "additionalProperties": true,
        "properties": {
          "awarder": {
            "description": "e.g. Time Magazine",
            "type": "string"
          },
          "date": {
            "$ref": "#/definitions/iso8601"
          },
          "summary": {
            "description": "e.g. Received for my work with Quantum Physics",
            "type": "string"
          },
          "title": {
            "description": "e.g. One of the 100 greatest minds of the century",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "basics": {
      "additionalProperties": true,
      "properties": {
        "email": {
          "description": "e.g. thomas@gmail.com",
          "format": "email",
          "type": "string"
        },
        "image": {
          "description": "URL (as per RFC 3986) to a image in JPEG or PNG format",
          "type": "string"
        },
        "label": {
          "description": "e.g. Web Developer",
          "type": "string"
        },
        "location": {
          "additionalProperties": true,
          "properties": {
            "address": {
              "description": "To add multiple address lines, use \n. For example, 1234 Glücklichkeit Straße\nHinterhaus 5. Etage li.",
              "type": "string"
            },
            "city": {
              "type": "string"
            },
            "countryCode": {
              "description": "code as per ISO-3166-1 ALPHA-2, e.g. US, AU, IN",
              "type": "string"
            },
            "postalCode": {
              "type": "string"
            },
            "region": {
              "description": "The general region where you live. Can be a US state, or a province, for instance.",
              "type": "string"
            }
          },
          "type": "object"
        },
        "name": {
          "type": "string"
        },
        "phone": {
          "description": "Phone numbers are stored as strings so use any format you like, e.g. 712-117-2923",
          "type": "string"
        },
        "profiles": {
          "additionalItems": false,
          "description": "Specify any number of social networks that you participate in",
          "items": {
            "additionalProperties": true,
            "properties": {
              "network": {
                "description": "e.g. Facebook or Twitter",
                "type": "string"
              },
              "url": {
                "description": "e.g. http://twitter.example.com/neutralthoughts",
                "format": "uri",
                "type": "string"
              },
              "username": {
                "description": "e.g. neutralthoughts",
                "type": "string"
              }
            },
            "type": "object"
          },
          "type": "array"
        },
        "summary": {
          "description": "Write a short 2-3 sentence biography about yourself",
          "type": "string"
        },
        "url": {
          "description": "URL (as per RFC 3986) to your website, e.g. personal homepage",
          "format": "uri",
          "type": "string"
        }
      },
      "type": "object"
    },
    "certificates": {
      "additionalItems": false,
      "description": "Specify any certificates you have received throughout your professional career",
      "items": {
        "additionalProperties": true,
        "properties": {
          "date": {
            "description": "e.g. 1989-06-12",
            "format": "date",
            "type": "string"
          },
          "issuer": {
            "description": "e.g. CNCF",
            "type": "string"
          },
          "name": {
            "description": "e.g. Certified Kubernetes Administrator",
            "type": "string"
          },
          "url": {
            "description": "e.g. http://example.com",
            "format": "uri",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "education": {
      "additionalItems": false,
      "items": {
        "additionalProperties": true,
        "properties": {
          "area": {
            "description": "e.g. Arts",
            "type": "string"
          },
          "courses": {
            "additionalItems": false,
            "description": "List notable courses/subjects",
            "items": {
              "description": "e.g. H1302 - Introduction to American history",
              "type": "string"
            },
            "type": "array"
          },
          "endDate": {
            "$ref": "#/definitions/iso8601"
          },
          "institution": {
            "description": "e.g. Massachusetts Institute of Technology",
            "type": "string"
          },
          "score": {
            "description": "grade point average, e.g. 3.67/4.0",
            "type": "string"
          },
          "startDate": {
            "$ref": "#/definitions/iso8601"
          },
          "studyType": {
            "description": "e.g. Bachelor",
            "type": "string"
          },
          "url": {
            "description": "e.g. http://facebook.example.com",
            "format": "uri",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "interests": {
      "additionalItems": false,
      "items": {
        "additionalProperties": true,
        "properties": {
          "keywords": {
            "additionalItems": false,
            "items": {
              "description": "e.g. Friedrich Nietzsche",
              "type": "string"
            },
            "type": "array"
          },
          "name": {
            "description": "e.g. Philosophy",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "languages": {
      "additionalItems": false,
      "description": "List any other languages you speak",
      "items": {
        "additionalProperties": true,
        "properties": {
          "fluency": {
            "description": "e.g. Fluent, Beginner",
            "type": "string"
          },
          "language": {
            "description": "e.g. English, Spanish",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "meta": {
      "additionalProperties": true,
      "description": "The schema version and any other tooling configuration lives here",
      "properties": {
        "canonical": {
          "description": "URL (as per RFC 3986) to latest version of this document",
          "format": "uri",
          "type": "string"
        },
        "lastModified": {
          "description": "Using ISO 8601 with YYYY-MM-DDThh:mm:ss",
          "type": "string"
        },
        "version": {
          "description": "A version field which follows semver - e.g. v1.0.0",
          "type": "string"
        }
      },
      "type": "object"
    },
    "projects": {
      "additionalItems": false,
      "description": "Specify career projects",
      "items": {
        "additionalProperties": true,
        "properties": {
          "description": {
            "description": "Short summary of project. e.g. Collated works of 2017.",
            "type": "string"
          },
          "endDate": {
            "$ref": "#/definitions/iso8601"
          },
          "entity": {
            "description": "Specify the relevant company/entity affiliations e.g. 'greenpeace', 'corporationXYZ'",
            "type": "string"
          },
          "highlights": {
            "additionalItems": false,
            "description": "Specify multiple features",
            "items": {
              "description": "e.g. Directs you close but not quite there",
              "type": "string"
            },
            "type": "array"
          },
          "keywords": {
            "additionalItems": false,
            "description": "Specify special elements involved",
            "items": {
              "description": "e.g. AngularJS",
              "type": "string"
            },
            "type": "array"
          },
          "name": {
            "description": "e.g. The World Wide Web",
            "type": "string"
          },
          "roles": {
            "additionalItems": false,
            "description": "Specify your role on this project or in company",
            "items": {
              "description": "e.g. Team Lead, Speaker, Writer",
              "type": "string"
            },
            "type": "array"
          },
          "startDate": {
            "$ref": "#/definitions/iso8601"
          },
          "type": {
            "description": " e.g. 'volunteering', 'presentation', 'talk', 'application', 'conference'",
            "type": "string"
          },
          "url": {
            "description": "e.g. http://www.computer.org/csdl/mags/co/1996/10/rx069-abs.html",
            "format": "uri",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "publications": {
      "additionalItems": false,
      "description": "Specify your publications through your career",
      "items": {
        "additionalProperties": true,
        "properties": {
          "name": {
            "description": "e.g. The World Wide Web",
            "type": "string"
          },
          "publisher": {
            "description": "e.g. IEEE, Computer Magazine",
            "type": "string"
          },
          "releaseDate": {
            "$ref": "#/definitions/iso8601"
          },
          "summary": {
            "description": "Short summary of publication. e.g. Discussion of the World Wide Web, HTTP, HTML.",
            "type": "string"
          },
          "url": {
            "description": "e.g. http://www.computer.org.example.com/csdl/mags/co/1996/10/rx069-abs.html",
            "format": "uri",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "references": {
      "additionalItems": false,
      "description": "List references you have received",
      "items": {
        "additionalProperties": true,
        "properties": {
          "name": {
            "description": "e.g. Timothy Cook",
            "type": "string"
          },
          "reference": {
            "description": "e.g. Joe blogs was a great employee, who turned up to work at least once a week. He exceeded my expectations when it came to doing nothing.",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "skills": {
      "additionalItems": false,
      "description": "List out your professional skill-set",
      "items": {
        "additionalProperties": true,
        "properties": {
          "keywords": {
            "additionalItems": false,
            "description": "List some keywords pertaining to this skill",
            "items": {
              "description": "e.g. HTML",
              "type": "string"
            },
            "type": "array"
          },
          "level": {
            "description": "e.g. Master",
            "type": "string"
          },
          "name": {
            "description": "e.g. Web Development",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "volunteer": {
      "additionalItems": false,
      "items": {
        "additionalProperties": true,
        "properties": {
          "endDate": {
            "$ref": "#/definitions/iso8601"
          },
          "highlights": {
            "additionalItems": false,
            "description": "Specify accomplishments and achievements",
            "items": {
              "description": "e.g. Increased profits by 20% from 2011-2012 through viral advertising",
              "type": "string"
            },
            "type": "array"
          },
          "organization": {
            "description": "e.g. Facebook",
            "type": "string"
          },
          "position": {
            "description": "e.g. Software Engineer",
            "type": "string"
          },
          "startDate": {
            "$ref": "#/definitions/iso8601"
          },
          "summary": {
            "description": "Give an overview of your responsibilities at the company",
            "type": "string"
          },
          "url": {
            "description": "e.g. http://facebook.example.com",
            "format": "uri",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "work": {
      "additionalItems": false,
      "items": {
        "additionalProperties": true,
        "properties": {
          "description": {
            "description": "e.g. Social Media Company",
            "type": "string"
          },
          "endDate": {
            "$ref": "#/definitions/iso8601"
          },
          "highlights": {
            "additionalItems": false,
            "description": "Specify multiple accomplishments",
            "items": {
              "description": "e.g. Increased profits by 20% from 2011-2012 through viral advertising",
              "type": "string"
            },
            "type": "array"
          },
          "location": {
            "description": "e.g. Menlo Park, CA",
            "type": "string"
          },
          "name": {
            "description": "e.g. Facebook",
            "type": "string"
          },
          "position": {
            "description": "e.g. Software Engineer",
            "type": "string"
          },
          "startDate": {
            "$ref": "#/definitions/iso8601"
          },
          "summary": {
            "description": "Give an overview of your responsibilities at the company",
            "type": "string"
          },
          "url": {
            "description": "e.g. http://facebook.example.com",
            "format": "uri",
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    }
  },
  "title": "Resume Schema",
  "type": "object"
}

=== pitecus/meirelles/src/assets/leo-meirelles.json
{
  "awards": [
    {
      "awarder": "Company",
      "date": "2014-11-01",
      "summary": "There is no spoon.",
      "title": "Award"
    }
  ],
  "basics": {
    "email": "pitecus@gmail.com",
    "label": "Angular + DevOps",
    "location": {
      "address": "5 Greenbrier ct",
      "city": "Wayne",
      "countryCode": "US",
      "postalCode": "07470",
      "region": "New Jersey"
    },
    "name": "Leonardo Meirelles",
    "phone": "(770) 298-3632",
    "picture": "leo-meirelles.jpeg",
    "profiles": [
      {
        "network": "Twitter",
        "url": "https://twitter.com/eyeeyesir",
        "username": "@eyeeyesir"
      },
      {
        "network": "LinkedIn",
        "url": "https://www.linkedin.com/in/leo-meirelles/",
        "username": "Leo Meirelles"
      }
    ],
    "summary": "Passionate for quality, creativity, and good design (code and UI), problem solving oriented professional with extensive experience in web/server architecture and development, a team player with excellent communication skills. I enjoy working in a dynamic environment which provides opportunities for new technical solutions. My skill set covers Linux, full stack Javascript (MongoDB, ExpressJS, AngularJS, NodeJS), Front End and Back End architecture and development.",
    "website": "https://pitecus.github.io"
  },
  "education": [
    {
      "area": "Computer Science",
      "courses": [],
      "endDate": "2004-08-14",
      "gpa": "",
      "institution": "Pontifícia Universidade Católica (PUCRS)",
      "startDate": "1998-07-06",
      "studyType": "Bachelor"
    }
  ],
  "interests": [
    {
      "keywords": [
        "Ferrets",
        "Unicorns"
      ],
      "name": "Wildlife"
    }
  ],
  "languages": [
    {
      "fluency": "Native speaker",
      "language": "Portugues"
    },
    {
      "fluency": "Native speaker",
      "language": "English"
    }
  ],
  "publications": [
    {
      "name": "Publication",
      "publisher": "Company",
      "releaseDate": "2014-10-01",
      "summary": "Description...",
      "website": "http://publication.com"
    }
  ],
  "references": [
    {
      "name": "Jane Doe",
      "reference": "Reference..."
    }
  ],
  "skills": [
    {
      "keywords": [
        "Linux",
        "full stack Javascript",
        "MongoDB",
        "MySQL",
        "Ajax",
        "JSON",
        "SOAP",
        "Advanced Bash shell script",
        "Sed",
        "Awk",
        "HTML",
        "CSS",
        "XML",
        "XSLT",
        "PPML",
        "C",
        "TCP/IP"
      ],
      "level": "Master",
      "name": "Markup Languages / Programming"
    },
    {
      "keywords": [
        "MEAN stack: MongoDB, ExpressJS, AngularJS, NodeJS.",
        "Frontend experience with EmberJS and BackboneJS",
        "Backend with Express",
        "Automated development using Grunt and Gulp",
        "Other libraries like D3,Karma, Mocha"
      ],
      "level": "Master",
      "name": "Javascript Frameworks"
    },
    {
      "keywords": [
        "OmniGraffle",
        "Google Analytics",
        "AWS instances",
        "version control (Github, SVN)",
        "Hudson",
        "Jenkins"
      ],
      "level": "Master",
      "name": "Software"
    },
    {
      "keywords": [
        "Chrome",
        "Firefox",
        "Safari",
        "Internet Explorer"
      ],
      "level": "Master",
      "name": "Browsers"
    }
  ],
  "volunteer": [
    {
      "endDate": "2013-01-01",
      "highlights": [
        "Awarded 'Volunteer of the Month'"
      ],
      "organization": "Organization",
      "position": "Volunteer",
      "startDate": "2012-01-01",
      "summary": "Description...",
      "website": "http://organization.com/"
    }
  ],
  "work": [
    {
      "company": "ADP",
      "endDate": "Current",
      "highlights": [
        "GitOps for CI/CD",
        "Continuous E2E tests using SauceLabs",
        "Replace an Adobe Flash application using Angular, parsing XML and using HighCharts.",
        "Create an application to identify incorrect paychecks using AWS Lambda (backend) and Kubernetes Helm Charts (frontend)",
        "Scan containers on CI/CD process for vulnerabilities"
      ],
      "position": "Principal Architect",
      "startDate": "2018-09-21",
      "summary": "Improving releases and development process. Design, build and deploy applications. Architect integration solutions.",
      "website": "https://www.adp.com"
    },
    {
      "company": "ADP",
      "endDate": "2018-09-21",
      "highlights": [
        "Managed the front end development of Global Cloud Connects with 30 developers."
      ],
      "position": "Principal Software Engineer",
      "startDate": "2016-10-01",
      "summary": "Focus in one application and improving it",
      "website": "https://www.adp.com"
    },
    {
      "company": "Google",
      "endDate": "2016-10-01",
      "highlights": [
        "Architect, design and integrate AngularJS 1.4 components for Cloud SQL inside Google Cloud Platform. Use Google Analytics to improve user experience by evaluating and prioritizing features.",
        "Coordinate with Google Site Reliability Engineering, project manager and back-end API team to prioritize bugs, features and release using experiments. Provide support for internal and external users. Create utility tools in Bash shell script, NodeJS and Chrome Extensions for internal usage."
      ],
      "position": "Senior Software Engineer",
      "startDate": "2015-05-04",
      "summary": "Frontend development, API integration, release new features",
      "website": "https://www.google.com"
    },
    {
      "company": "The New York Times",
      "endDate": "2015-04-30",
      "highlights": [
        "Create new features, improve system’s performance and develop new applications in Business Intelligence analytics ecosystem. Develop software prototypes to streamline data access. Responsible for tag management and tracking systems for page and modules views, customer behavior, A/B testings, and subscription funnel.",
        "Develop in MEAN stack. Enhance tracking data through systems integration. Create front-end applications for user friendly interaction with REST services. Partner with multiple stakeholders to prioritize features and manage development cycles."
      ],
      "position": "Senior Software Engineer",
      "startDate": "2013-06-01",
      "summary": "Frontend development, API integration, Business Inteligence, user behavior analysis",
      "website": "https://www.nytimes.com"
    },
    {
      "company": "The New York Times",
      "endDate": "2013-06-01",
      "highlights": [
        "System architect for NYTimes-China site: planned the infra-structure, built the servers and successfully transitioned to the implementation team. Developed SEO (search engine optimization) features using ModEST publishing framework. Worked on Datacenter Move (DCI) project, providing solutions for server configurations migration between iPlanet and Apache.",
        "Provided support and development for NY Times web site. Responsible for performance, stability and improvement of hundreds of servers in Production in two Datacenters (East and West) with millions of daily page views."
      ],
      "position": "Web Engineer",
      "startDate": "2011-10-17",
      "summary": "DevOps, Production Support, frontend development, performance improvements",
      "website": "https://www.nytimes.com"
    },
    {
      "company": "ADP",
      "endDate": "2011-10-14",
      "highlights": [
        "Architect and design reusable components using Dojo, Java and Javascript. Develop UI web front ends, middle tier JSF to provide communication, security and performance to Web Services using SOAP. Generate code with cross browser compatibility for Firefox, Internet Explorer (7, 8 and 9) and Safari.",
        "Provided analysis of new product features, advice about performance improvements and usability with business and analysis teams, review UI under development and create web applications in tight deadlines, with emphasis in high availability, low resources usage, security and performance."
      ],
      "position": "Lead Technical Analyst",
      "startDate": "2008-12-08",
      "summary": "Full stack development with Java and Javascript. Cross browser compatibility. Performance improvements.",
      "website": "https://www.adp.com"
    },
    {
      "company": "ADP",
      "endDate": "2008-12-08",
      "highlights": [
        "Provided 3rd level support to ADP US Portal. The ADP Portal was developed under J2EE and had more than 5 millions of active users with an average of 2 millions of daily hits, providing a common interface to many enterprise products.",
        "Responsible for administration and monitoring of several production and pre-production servers, troubleshoot and coordinate teams to fix issues efficiently. Provided technical support for other teams regarding WebSphere Portal environment and fixed security issues found during penetration tests."
      ],
      "position": "Senior programmer",
      "startDate": "2006-11-01",
      "summary": "Production support, release management, coordinate troubleshooting cross-teams",
      "website": "https://www.adp.com.br"
    },
    {
      "company": "ADP",
      "endDate": "2006-11-01",
      "highlights": [
        "Developed and designed using Scrum methodology a product tailored for US human resources, including payroll, vacations and benefits. The system was based in JSP and Struts, with the front-end running inside WebSphere Portal. Used jUnit tests for reliability, quality and integration tests."
      ],
      "position": "Programmer",
      "startDate": "2005-04-11",
      "summary": "Java developer, unit tests.",
      "website": "https://www.adp.com.br"
    }
  ]
}
